# Generated by Django 4.0.4 on 2022-05-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reminder", "0003_remindermessage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ReminderMessage",
        ),
        migrations.RemoveField(
            model_name="birthdays",
            name="current_date",
        ),
        migrations.RemoveField(
            model_name="birthdays",
            name="friends_birthdate",
        ),
        migrations.AddField(
            model_name="birthdays",
            name="day_of_birth",
            field=models.IntegerField(default=12, max_length=2),
        ),
        migrations.AddField(
            model_name="birthdays",
            name="month_of_birth",
            field=models.IntegerField(default=11, max_length=2),
        ),
        migrations.AddField(
            model_name="birthdays",
            name="year_of_birth",
            field=models.IntegerField(default=2000, max_length=4),
        ),
    ]
